apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
bases:
  - ../../base/
resources:
  - kiali-ingress.yaml
  - prometheus-ingress.yaml
  - grafana-ingress.yaml
  - jaeger-ingress.yaml
patchesStrategicMerge:
  - default.yaml