apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
bases:
  - ../../base/
resources:
  - kiali-lb.yaml
  - prometheus-lb.yaml
  - grafana-lb.yaml
  - jaeger-lb.yaml
patchesStrategicMerge:
  - default.yaml
